# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981306f6fbd026622c92be5d3463d33edc32bc2448f6ca561d1d3536d6ee27912d00dcafba953a089bf467f166dafd961603eb6c422de514e403fa9303abcfa3

test:
  secret_key_base: d6cafe2c55539046e72aafaee13fb041410e3aeab51ad6f1618f5c7d6b5c8b1534bc4a86401e418f32862a9efced73e31d1289f9100db8c2c65ce2fff80990b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
